apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-registration
  namespace: student-app
spec:
  replicas: 2
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 300
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: student-registration
  template:
    metadata:
      labels:
        app: student-registration
    spec:
      serviceAccountName: student-app-ksa
      containers:
        - name: application
          image: asia-south1-docker.pkg.dev/pe3-devops-training-tkaturi/pe3-app-images/student-registration:285cdb0cc14893dfa346de40231db9bb73abd30b
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
          env:
            - {name: PORT, value: "3000"}
            - {name: DB_HOST, value: "127.0.0.1"}
            - {name: DB_PORT, value: "3306"}
            - {name: DB_NAME, value: "studentdb"}
            - {name: GCS_BUCKET_NAME, value: "pe3-teja-zap-files-870472427005"}
            - name: DB_USER
              valueFrom:
                secretKeyRef: {name: student-db-credentials, key: DB_USER}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef: {name: student-db-credentials, key: DB_PASSWORD}
          startupProbe:
            httpGet: {path: /health, port: http}
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 30
          readinessProbe:
            httpGet: {path: /readyz, port: http}
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 6
          livenessProbe:
            httpGet: {path: /healthz, port: http}
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests: {cpu: 100m, memory: 128Mi}
            limits: {cpu: 500m, memory: 512Mi}
        - name: cloud-sql-auth-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.25.2
          args: ["--private-ip", "--structured-logs", "--port=3306", "pe3-devops-training-tkaturi:asia-south1:pe3-teja-zap-mysql"]
          securityContext: {runAsNonRoot: true}
          resources:
            requests: {cpu: 100m, memory: 128Mi}
            limits: {cpu: 250m, memory: 256Mi}
