apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: student-registration-health-check
  namespace: student-app
spec:
  default:
    checkIntervalSec: 15
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3

    config:
      type: HTTP

      httpHealthCheck:
        port: 3000
        requestPath: /healthz

  targetRef:
    group: ""
    kind: Service
    name: student-registration-service
