apiVersion: v1
kind: ServiceAccount
metadata:
  name: student-app-ksa
  namespace: student-app
  annotations:
    iam.gke.io/gcp-service-account: student-app-runtime-sa@pe3-devops-training-tkaturi.iam.gserviceaccount.com
